name: Deploy
on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22

    - name: build
      run: nix build

    - name: Adjust permissions
      run: |
        chown -R `id -u`:`id -g` ./result
        chmod -R a+rwx ./result

    - name: upload
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./result

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: deploy      # The branch the action should deploy to.
        folder: _build/html # The folder the action should deploy.
